//PLAYER 
PLAYER_STROKE_COLOR = "#93d3bf";
PLAYER_STROKE_WIDTH = 3;

PLAYER_SHADOW_COLOR = "#93d3bf";
PLAYET_SHADOW_BLUR = 20;

PLAYER_RADIUS = 50;

PLAYER_BASE_HEALTH = 100;
PLAYER_BASE_RANGE = 500;
PLAYER_RANGE_CIRCLE_COLOR = "#93d3bf";
PLAYER_RANGE_CIRCLE_WIDTH = 5;

//WAVE
WAVE_STARTING_RANGE = 1500;
WAVE_DURATION = 20 * 1000;
WAVE_DENSITY = 50;
WAVE_SPAWN_INTERVAL = 100;
WAVE_BREAK_DURATION = 5 * 1000;

//ENEMY
ENEMY_BASIC_SPEED = 100; // 100px per second 
ENEMY_BASIC_HEALTH = 5;
ENEMY_BASIC_DAMAGE = 15;

ENEMY_BASIC_WIDTH = 10;
ENEMY_BASIC_HEIGHT = 10;

ENEMY_BASIC_STROKE_COLOR = "#e91e63";
ENEMY_BASIC_STROKE_WIDTH = 2;
ENEMY_BASIC_SHADOW_COLOR = "#e91e63";
ENEMY_BASIC_SHADOW_BLUR = 10;

//DEFAULT
DEFAULT_SHADOW_COLOR = "#00000000";
DEFAULT_SHADOW_BLUR = 0;